SELECT kna.KAITO_NIGHT_ACT_ID, kna.FROM_GAME_PARTICIPATION_ID, kna.TO_GAME_PARTICIPATION_ID
FROM KAITO_NIGHT_ACT as kna
JOIN GAME_PARTICIPATION as gp ON gp.GAME_PARTICIPATION_ID = kna.FROM_GAME_PARTICIPATION_ID
WHERE gp.GAME_ID = /*gameId*/'1'
LIMIT 1