{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.3.4.RELEASE.jar",
          "url": "spring-boot-gradle-plugin-2.3.4.RELEASE.jar",
          "size": 101988,
          "sha512": "a75501f8bed7a656b20561b9244de3801916002926160cd42a9b28c460d1b7331df1aa8d7e6b60095b209d3594c73ac8bad3dc3a9af958013ed638c2a27d7044",
          "sha256": "0df3004d910f8ffbfea64d56c407f37bb0924da50f173e2c5d1c5edcd66c5d9f",
          "sha1": "6e5ac8239da1b313458a12ce8ad3dda53276a7ea",
          "md5": "d8651784082a5c263445defad1bfac55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.0.10.RELEASE"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.3.4.RELEASE.jar",
          "url": "spring-boot-gradle-plugin-2.3.4.RELEASE.jar",
          "size": 101988,
          "sha512": "a75501f8bed7a656b20561b9244de3801916002926160cd42a9b28c460d1b7331df1aa8d7e6b60095b209d3594c73ac8bad3dc3a9af958013ed638c2a27d7044",
          "sha256": "0df3004d910f8ffbfea64d56c407f37bb0924da50f173e2c5d1c5edcd66c5d9f",
          "sha1": "6e5ac8239da1b313458a12ce8ad3dda53276a7ea",
          "md5": "d8651784082a5c263445defad1bfac55"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-gradle-plugin-2.3.4.RELEASE-javadoc.jar",
          "size": 186012,
          "sha512": "10bd9e59829f2063bf093b1d5fe917faa8367a410e52ff16b39c8483fe9846cceb82618f403779d52bbcaaf2a3a0be29b4e53e59d1905a7f9de755477180163f",
          "sha256": "4d0d9dbfcfff2dd20a3cbadb87d714cd7dd2aaf3eb0e45b162b0456fb921ad1c",
          "sha1": "3d5ac0f4d5e3bb69bc80a228a16dadd4552f855d",
          "md5": "57083da76b29f46fc550f7b69c87b601"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-gradle-plugin-2.3.4.RELEASE-sources.jar",
          "size": 63896,
          "sha512": "e69b13d4b2d6d040ec46ff8c569098b61c0d6567855d587a272f41b73712fa3f90828d5cb4b8556a10f846ece47eac7a49ba148cb5fc3a99e951cc67b1961add",
          "sha256": "c38102f90da69e503e43d1cba6717627b784fd109ef6f16c251dadfa82103b53",
          "sha1": "b27761876fce251fd30928c7923e14662d26e820",
          "md5": "421b48727d70c08fb11d4adf47b49a9a"
        }
      ]
    }
  ]
}
