{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.3.4.RELEASE.jar",
          "url": "spring-boot-buildpack-platform-2.3.4.RELEASE.jar",
          "size": 182755,
          "sha512": "aa03c49f7ce8b157abfb50224e38ec3f38f86a8174a151ff724fc739db46e7cc430bac1bec085e1acaa5fd99c8a7bd5461d6838ad28517b8140e22d4fc12733f",
          "sha256": "9ef0629ce6150c707050ca4b95b74c33705937b7e67e3478c56b4c7e4230b4c4",
          "sha1": "6cc317cb422a7c74a21b4700374690f411e909cc",
          "md5": "2a8d630b892c6945f2d5ef14884dbc82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.3.4.RELEASE.jar",
          "url": "spring-boot-buildpack-platform-2.3.4.RELEASE.jar",
          "size": 182755,
          "sha512": "aa03c49f7ce8b157abfb50224e38ec3f38f86a8174a151ff724fc739db46e7cc430bac1bec085e1acaa5fd99c8a7bd5461d6838ad28517b8140e22d4fc12733f",
          "sha256": "9ef0629ce6150c707050ca4b95b74c33705937b7e67e3478c56b4c7e4230b4c4",
          "sha1": "6cc317cb422a7c74a21b4700374690f411e909cc",
          "md5": "2a8d630b892c6945f2d5ef14884dbc82"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-buildpack-platform-2.3.4.RELEASE-javadoc.jar",
          "size": 245297,
          "sha512": "349a26669a949e7d05860f86f78ebafe3420de2e6450f7d29d80e79de2a63fe70c64ce6de7a2f4f78da527d6f75e45d75068ffee23d3928ef443af855cbd0bd3",
          "sha256": "3bc4cdb51bc3db24c7a8d1ce9c11db30e22c5d507fc6976d02451ccaa6ae4127",
          "sha1": "861b54e1bec605aa685aee6bb8515e9fb7021455",
          "md5": "e9faf3dbfcc7e21cadf3377b9f1a08a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-buildpack-platform-2.3.4.RELEASE-sources.jar",
          "size": 118378,
          "sha512": "a30a290f949873a5df3e89036d87aa516182193c6b8d890b34a9a1aaebdeb316e088088a1a02de59769bf0dde92723d3ba86b8826570926deb5f659b93777d81",
          "sha256": "42f7877bd2dc117efd3786eea7313abaaf8a740b13555d56eb54438d43023bba",
          "sha1": "6e415ae9687df700ed8e3279bf862d829282c5ee",
          "md5": "b4df4452e313f84b355c1daaab8b9b81"
        }
      ]
    }
  ]
}
