{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "5.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "6z5e52fxwrbhlhwdrxkyhcdiiu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.6.2.jar",
          "url": "junit-jupiter-params-5.6.2.jar",
          "size": 562271,
          "sha512": "5f44d4c9bbfd6ca37bfffd2f2c8b8c9fa9fa58c163104c27526f92689d1031e925875251288b92bf946941359aab17083e70443d6172917853ecb6da36e451fc",
          "sha256": "52f7aeb346cfa41bb33a8d3dbab8c577f9c37f8f5a79a632af10b5c8f1e92186",
          "sha1": "f2a64a42cf73077062c2386db0598062b7480d91",
          "md5": "0dc5639e8cfec8b920869f1ee16746c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.6.2.jar",
          "url": "junit-jupiter-params-5.6.2.jar",
          "size": 562271,
          "sha512": "5f44d4c9bbfd6ca37bfffd2f2c8b8c9fa9fa58c163104c27526f92689d1031e925875251288b92bf946941359aab17083e70443d6172917853ecb6da36e451fc",
          "sha256": "52f7aeb346cfa41bb33a8d3dbab8c577f9c37f8f5a79a632af10b5c8f1e92186",
          "sha1": "f2a64a42cf73077062c2386db0598062b7480d91",
          "md5": "0dc5639e8cfec8b920869f1ee16746c2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.6.2-javadoc.jar",
          "url": "junit-jupiter-params-5.6.2-javadoc.jar",
          "size": 583178,
          "sha512": "fc6ef4890ce1b3b0dcd4d7882172b75d97c64d457e2a09761ba1d44c8b54237e65caa195cab087cc5612a288db80b3d8825374371774fd985225ee98a80db03e",
          "sha256": "e0324527f3ccfa1072d9f5e06b0e66f7d97e6cc4ed00c58d0cab7d954b3a3570",
          "sha1": "89df3ba1bee8a7374ce7638aa4500aabacb94833",
          "md5": "797b70c3b30c870d74e9f52c78050ef2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.6.2-sources.jar",
          "url": "junit-jupiter-params-5.6.2-sources.jar",
          "size": 64747,
          "sha512": "f68f5daa7c992dfbdf9d6374cea4401f4e4a1a83c9bafec76a349ac8a75b1bf776772c77245bcd181fbfa6214418edde3490822e92c0f1314a0a7ebe105b1a15",
          "sha256": "f37036c4adadc392687db8e44150ed1629a3c30ea11875805254ae96c8447ba1",
          "sha1": "f09c69685e20753eaf05577f5da1f9a220783def",
          "md5": "9ec17cef6aad02a1be5fd494f582b6f8"
        }
      ]
    }
  ]
}
