{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-2.3.4.RELEASE.jar",
          "url": "spring-boot-loader-tools-2.3.4.RELEASE.jar",
          "size": 242402,
          "sha512": "e04db6686018b9531e4340c2d63df27bbab8594785c6dbe2137a86c5b45d9a5aad08ff6868666c24bfb729ff84af60ab6781e30ace757ab0985f17181536a644",
          "sha256": "859b6548b5a3dc3229eab3400c57e162a0b8a50993fe1af85cd438664d5f4e05",
          "sha1": "823d57ef05ca69584db72d45eeee93bb0adef0b6",
          "md5": "1a21bc12c489c990d5e98ad705179182"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-2.3.4.RELEASE.jar",
          "url": "spring-boot-loader-tools-2.3.4.RELEASE.jar",
          "size": 242402,
          "sha512": "e04db6686018b9531e4340c2d63df27bbab8594785c6dbe2137a86c5b45d9a5aad08ff6868666c24bfb729ff84af60ab6781e30ace757ab0985f17181536a644",
          "sha256": "859b6548b5a3dc3229eab3400c57e162a0b8a50993fe1af85cd438664d5f4e05",
          "sha1": "823d57ef05ca69584db72d45eeee93bb0adef0b6",
          "md5": "1a21bc12c489c990d5e98ad705179182"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-loader-tools-2.3.4.RELEASE-javadoc.jar",
          "size": 167003,
          "sha512": "49c88848b074c053d3c13172dc83483c96bd070a86fe7167f62b9d6ef01f572c46bdcc3e54deb0bc94d552351e5c6c3b34e9f8671ead9453c64f0e488c15a7cf",
          "sha256": "1b3af7e1d5fd3d5a34dd0527c8d1d49b1afa89d92722dc4150d4e3dc7032d73a",
          "sha1": "50f093722e62b14a115a4ef2620b01bd2ce923db",
          "md5": "ff9e231182b478ecd118b48433168358"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-loader-tools-2.3.4.RELEASE-sources.jar",
          "size": 207598,
          "sha512": "8238e43894f77dd92f66219c5bcfee4b2ac52dfe2e38bbb92e103dab6050403df63a4527536a54eae0b0783f9669f7572a225a7cd534d42ddabeedc07b029197",
          "sha256": "be181594081cea540e729bc113cc42c78965a6df060d1f031afb8f8085cfad49",
          "sha1": "4912026bdadabc40a435028c052df6575ec36d70",
          "md5": "9a61da564eb112555e6e042b8b7c0cd6"
        }
      ]
    }
  ]
}
