{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.3.4.RELEASE.jar",
          "url": "spring-boot-test-autoconfigure-2.3.4.RELEASE.jar",
          "size": 175155,
          "sha512": "c75b75a10d4410b0c55c90d130de96290eb109f18c40354ead196d22d7c10eb6e03f92410bed40488a592c564d82c2399aa47a85856815c950e0cda9762aa74b",
          "sha256": "d510fced347f158431cac3f23a8766b019d2df3b02c9c2397b6bd6433b5e6e0d",
          "sha1": "fdfe878383124d96d477ceba4799eb546cfbdf3d",
          "md5": "b4edaeac1aa3c3026176e98b82c42dd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.3.4.RELEASE.jar",
          "url": "spring-boot-test-autoconfigure-2.3.4.RELEASE.jar",
          "size": 175155,
          "sha512": "c75b75a10d4410b0c55c90d130de96290eb109f18c40354ead196d22d7c10eb6e03f92410bed40488a592c564d82c2399aa47a85856815c950e0cda9762aa74b",
          "sha256": "d510fced347f158431cac3f23a8766b019d2df3b02c9c2397b6bd6433b5e6e0d",
          "sha1": "fdfe878383124d96d477ceba4799eb546cfbdf3d",
          "md5": "b4edaeac1aa3c3026176e98b82c42dd5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-2.3.4.RELEASE-javadoc.jar",
          "size": 340838,
          "sha512": "eb3b60212ddc4b864f76f56c0bb813fbb8c8628ab6e7d0f9637dce11f1bb8883d48c954109a25d7a5ad040da08df3748464edddba798528bd828ca406c4ab81c",
          "sha256": "3d5bb76e240d92ed153b3fc1ddc8b9a42734d6d89a799a488e7907769a7fec03",
          "sha1": "f326681a894ddebaef7f58e7106902cd32ce8e62",
          "md5": "7b3269aa4ebf803f8d90399fbaeb9c17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-test-autoconfigure-2.3.4.RELEASE-sources.jar",
          "size": 167311,
          "sha512": "45fcdbf0096b583200f567356859ecf94ff5960ac795e9ea1f5c5966cedef2ca43a0266220c62660cba20d298cff11809669a1ba3252e5a870c102e1e0e6da18",
          "sha256": "a16a4745be9ed2b5d91979d5b5f767e73ceefa289d37995bf7bf7959dcca287a",
          "sha1": "f73ceaf5f18e08a15e5266d4e0df1a1f6f563388",
          "md5": "e9f7ba6b088c858f0ca9454a1bf7ddf3"
        }
      ]
    }
  ]
}
