{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.3.4.RELEASE.jar",
          "url": "spring-boot-autoconfigure-2.3.4.RELEASE.jar",
          "size": 1476367,
          "sha512": "84a00e72797604103b5b5fbd377026b66bbdc489b46a78c11fe003bfdfeaa9756d209ea77880ef872af3ffe6e3c060c28ce7f552f77b93e7c7009bc0ce8c76e5",
          "sha256": "0c5645b638f3422d96411e4c47b6b5c217408d8e4314ff8fcb2aff29f7cba7a7",
          "sha1": "ff9efafb9d62c17d8c3c1faec7afad147c924263",
          "md5": "c0c96844ca3baffbaabe7743a45c700c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.3.4.RELEASE.jar",
          "url": "spring-boot-autoconfigure-2.3.4.RELEASE.jar",
          "size": 1476367,
          "sha512": "84a00e72797604103b5b5fbd377026b66bbdc489b46a78c11fe003bfdfeaa9756d209ea77880ef872af3ffe6e3c060c28ce7f552f77b93e7c7009bc0ce8c76e5",
          "sha256": "0c5645b638f3422d96411e4c47b6b5c217408d8e4314ff8fcb2aff29f7cba7a7",
          "sha1": "ff9efafb9d62c17d8c3c1faec7afad147c924263",
          "md5": "c0c96844ca3baffbaabe7743a45c700c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-autoconfigure-2.3.4.RELEASE-javadoc.jar",
          "size": 2251516,
          "sha512": "c47b5aa3a76b3b60c54cd103158cb9fc466c7ad18c93183cc5dc7d30495b90c795e274e16c5542c499466761654e9d42af50317b8c9e1079bd7a763e266c130c",
          "sha256": "c7c592cb74f3bf55131de784b4acb2f8f3513768cfb734226d605e4405dbaba8",
          "sha1": "8a2f6b3b71d909784455688012940ffb2f4a3cfa",
          "md5": "26015c73b5bf08195f4961d17f15f995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-autoconfigure-2.3.4.RELEASE-sources.jar",
          "size": 894933,
          "sha512": "7d68058d5233dd70ac6c002ae09d5020583a8febf44a7fa4865cff56c3c257ef74fbd8dde4e51143764e0c9875bd508cd2c279a02d97910ec6e46cb2a7c75018",
          "sha256": "a3d432d4ca99fc536a1c5746a5bad608ace0d74e6b154c2320ad7dcbef9ba192",
          "sha1": "ab1099fd038676548eb763db1d1176d1b92828d1",
          "md5": "a37949139f5b04fad49c0b209cb9aaa4"
        }
      ]
    }
  ]
}
