{
  "formatVersion": "1.0",
  "component": {
    "url": "../../okio-multiplatform/2.4.3/okio-multiplatform-2.4.3.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.5.1",
      "buildId": "dxwnt424xnhihaqbvrflyfyvpq"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.4.3.jar",
          "url": "okio-2.4.3.jar",
          "size": 241491,
          "sha1": "d946f785445d73c6bc99bbd778576d2576e37ea9",
          "md5": "ebcc87a81c6ba98049fa1e66798c81f9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.4.3.jar",
          "url": "okio-2.4.3.jar",
          "size": 241491,
          "sha1": "d946f785445d73c6bc99bbd778576d2576e37ea9",
          "md5": "ebcc87a81c6ba98049fa1e66798c81f9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.4.3/okio-metadata-2.4.3.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.4.3"
      }
    }
  ]
}
