{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-web-2.3.4.RELEASE.jar",
          "size": 4798,
          "sha512": "160c8b9df36b5013d1f387c67a462990b132ef6d988ee81d530ed32409929b4adaa49c041d89d34297df06c51694124faef807ec4abdd3dc5f1d800f6076972c",
          "sha256": "c57b8e6a75b57b71f520b834bc321c9314dbd31ad4b9297719b5e2d8c44e36cf",
          "sha1": "fe00611add5307c1f25f955b5229b7dddaaa2ff4",
          "md5": "ea1bea5b79bd4daa73f8f5750254688b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-web-2.3.4.RELEASE.jar",
          "size": 4798,
          "sha512": "160c8b9df36b5013d1f387c67a462990b132ef6d988ee81d530ed32409929b4adaa49c041d89d34297df06c51694124faef807ec4abdd3dc5f1d800f6076972c",
          "sha256": "c57b8e6a75b57b71f520b834bc321c9314dbd31ad4b9297719b5e2d8c44e36cf",
          "sha1": "fe00611add5307c1f25f955b5229b7dddaaa2ff4",
          "md5": "ea1bea5b79bd4daa73f8f5750254688b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-web-2.3.4.RELEASE-javadoc.jar",
          "size": 4798,
          "sha512": "160c8b9df36b5013d1f387c67a462990b132ef6d988ee81d530ed32409929b4adaa49c041d89d34297df06c51694124faef807ec4abdd3dc5f1d800f6076972c",
          "sha256": "c57b8e6a75b57b71f520b834bc321c9314dbd31ad4b9297719b5e2d8c44e36cf",
          "sha1": "fe00611add5307c1f25f955b5229b7dddaaa2ff4",
          "md5": "ea1bea5b79bd4daa73f8f5750254688b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-starter-web-2.3.4.RELEASE-sources.jar",
          "size": 4798,
          "sha512": "cf78e140c220793263741b08b964d3adace4d26017009d5fa2be2ac076e8346c59ea1e081d58d737cfa8536f8433e59fb4f41707cb11d3dc946acf2eff8068ce",
          "sha256": "5ff38e0dd6c3dab43eb20154a7a3c5243f72fa37d805c8dd2d8d4d9bd560aee2",
          "sha1": "e4cf4305b0aa3c837df28cc1c576b20339d28cd7",
          "md5": "f784d337f0c15a0db1fb56c201f327ed"
        }
      ]
    }
  ]
}
