{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-logging-2.3.4.RELEASE.jar",
          "size": 4754,
          "sha512": "b2c5266b8c07d15049ae61c67baf15922eff9d33ae82c69155c9b1235077122e00e56ff980579f5eaec38a4f51b72108cbbdd0ba1f434ac192234cb5cf190f1e",
          "sha256": "c1e9076f06df6e2b866812f33c7ae2936800c01846629d9247c327907416113e",
          "sha1": "677a66ac80e88cefaaca64e72b5523eb4836b7ae",
          "md5": "0f163d2e26f94457e2b31072ca57ea80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-logging-2.3.4.RELEASE.jar",
          "size": 4754,
          "sha512": "b2c5266b8c07d15049ae61c67baf15922eff9d33ae82c69155c9b1235077122e00e56ff980579f5eaec38a4f51b72108cbbdd0ba1f434ac192234cb5cf190f1e",
          "sha256": "c1e9076f06df6e2b866812f33c7ae2936800c01846629d9247c327907416113e",
          "sha1": "677a66ac80e88cefaaca64e72b5523eb4836b7ae",
          "md5": "0f163d2e26f94457e2b31072ca57ea80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-logging-2.3.4.RELEASE-javadoc.jar",
          "size": 4754,
          "sha512": "b2c5266b8c07d15049ae61c67baf15922eff9d33ae82c69155c9b1235077122e00e56ff980579f5eaec38a4f51b72108cbbdd0ba1f434ac192234cb5cf190f1e",
          "sha256": "c1e9076f06df6e2b866812f33c7ae2936800c01846629d9247c327907416113e",
          "sha1": "677a66ac80e88cefaaca64e72b5523eb4836b7ae",
          "md5": "0f163d2e26f94457e2b31072ca57ea80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-starter-logging-2.3.4.RELEASE-sources.jar",
          "size": 4754,
          "sha512": "b2c5266b8c07d15049ae61c67baf15922eff9d33ae82c69155c9b1235077122e00e56ff980579f5eaec38a4f51b72108cbbdd0ba1f434ac192234cb5cf190f1e",
          "sha256": "c1e9076f06df6e2b866812f33c7ae2936800c01846629d9247c327907416113e",
          "sha1": "677a66ac80e88cefaaca64e72b5523eb4836b7ae",
          "md5": "0f163d2e26f94457e2b31072ca57ea80"
        }
      ]
    }
  ]
}
