{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jdbc",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-jdbc-2.3.4.RELEASE.jar",
          "size": 4759,
          "sha512": "2f5db8e3a63f34e4bc58946a73dda5df5878bb3e7325c68a5d79d289a749df261129d042a9d97bef1254809a3683c002843bc51472c83f4cd347b4ea0f8c98ae",
          "sha256": "9111ff873d44c0ee7f8fa9b2f17b1098b3e01935dccb567f01b06bde84cdfb38",
          "sha1": "77ca3fe49c6f9bb62fec474ebfc0c529bf048fd4",
          "md5": "872ea19a90c51744016257109e60efe7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-jdbc-2.3.4.RELEASE.jar",
          "size": 4759,
          "sha512": "2f5db8e3a63f34e4bc58946a73dda5df5878bb3e7325c68a5d79d289a749df261129d042a9d97bef1254809a3683c002843bc51472c83f4cd347b4ea0f8c98ae",
          "sha256": "9111ff873d44c0ee7f8fa9b2f17b1098b3e01935dccb567f01b06bde84cdfb38",
          "sha1": "77ca3fe49c6f9bb62fec474ebfc0c529bf048fd4",
          "md5": "872ea19a90c51744016257109e60efe7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-jdbc-2.3.4.RELEASE-javadoc.jar",
          "size": 4759,
          "sha512": "2f5db8e3a63f34e4bc58946a73dda5df5878bb3e7325c68a5d79d289a749df261129d042a9d97bef1254809a3683c002843bc51472c83f4cd347b4ea0f8c98ae",
          "sha256": "9111ff873d44c0ee7f8fa9b2f17b1098b3e01935dccb567f01b06bde84cdfb38",
          "sha1": "77ca3fe49c6f9bb62fec474ebfc0c529bf048fd4",
          "md5": "872ea19a90c51744016257109e60efe7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-starter-jdbc-2.3.4.RELEASE-sources.jar",
          "size": 4759,
          "sha512": "08d1d5efae208ed7c78803cc153ef8f8b249673aa0c4129e80b34b7f5342a21f8f7a5ae0ec1583e504322ae05feaead7d0fcdd16347eb8e2a76c529e0a46c94e",
          "sha256": "aa65e4d113ea85c8c4a74e6f57e5ee6bc3dd805366ef8edc8990c05ed60744cc",
          "sha1": "a8fb82a533fa9fe23c66d7962aebb7dd84875b4b",
          "md5": "3e6d09aeb0ba5bb1a52a3bff354edab5"
        }
      ]
    }
  ]
}
