{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.38"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.38"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-tomcat-2.3.4.RELEASE.jar",
          "size": 4790,
          "sha512": "3263599e9aaf7ba494f82afe2503fd22604a0815513cd86662e1d6e2c9856e72de19cbd56218d25bd9678cc27840da0af3ad5c1689218ea8f876f19dc173778f",
          "sha256": "011aa5bdbd078c3ba6bbbecc709f9bdcf5442f319c71761f056dcb4eea930bc6",
          "sha1": "acffbb94a26dd1b7e9c38795797197e2dcb9d2e5",
          "md5": "2262439536e23953ba9bc3a476e8d0d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.38"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.38"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-tomcat-2.3.4.RELEASE.jar",
          "size": 4790,
          "sha512": "3263599e9aaf7ba494f82afe2503fd22604a0815513cd86662e1d6e2c9856e72de19cbd56218d25bd9678cc27840da0af3ad5c1689218ea8f876f19dc173778f",
          "sha256": "011aa5bdbd078c3ba6bbbecc709f9bdcf5442f319c71761f056dcb4eea930bc6",
          "sha1": "acffbb94a26dd1b7e9c38795797197e2dcb9d2e5",
          "md5": "2262439536e23953ba9bc3a476e8d0d8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.3.4.RELEASE-javadoc.jar",
          "size": 4790,
          "sha512": "3263599e9aaf7ba494f82afe2503fd22604a0815513cd86662e1d6e2c9856e72de19cbd56218d25bd9678cc27840da0af3ad5c1689218ea8f876f19dc173778f",
          "sha256": "011aa5bdbd078c3ba6bbbecc709f9bdcf5442f319c71761f056dcb4eea930bc6",
          "sha1": "acffbb94a26dd1b7e9c38795797197e2dcb9d2e5",
          "md5": "2262439536e23953ba9bc3a476e8d0d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-starter-tomcat-2.3.4.RELEASE-sources.jar",
          "size": 4790,
          "sha512": "3263599e9aaf7ba494f82afe2503fd22604a0815513cd86662e1d6e2c9856e72de19cbd56218d25bd9678cc27840da0af3ad5c1689218ea8f876f19dc173778f",
          "sha256": "011aa5bdbd078c3ba6bbbecc709f9bdcf5442f319c71761f056dcb4eea930bc6",
          "sha1": "acffbb94a26dd1b7e9c38795797197e2dcb9d2e5",
          "md5": "2262439536e23953ba9bc3a476e8d0d8"
        }
      ]
    }
  ]
}
