{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.16.1"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.junit.vintage",
          "module": "junit-vintage-engine",
          "version": {
            "requires": "5.6.2"
          },
          "excludes": [
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-test-2.3.4.RELEASE.jar",
          "size": 4782,
          "sha512": "b2228d3db38ca02ca953347c618ec82cb6f09d17c2e31593d94141d8da4bbf90b1cc3bd47a7f3676c9cb101623c509fc33387283cf0fc3789d4b0f00d5a88cf0",
          "sha256": "4fb342a8dcd186689adfd6746a3b2b03c4b930f3c8960e9585e7c5594cf3160f",
          "sha1": "a5fc832082202954b704ef4221a57a47adfb675f",
          "md5": "700fcefed717ce6e0385406dd8bfa8da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.16.1"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.junit.vintage",
          "module": "junit-vintage-engine",
          "version": {
            "requires": "5.6.2"
          },
          "excludes": [
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-test-2.3.4.RELEASE.jar",
          "size": 4782,
          "sha512": "b2228d3db38ca02ca953347c618ec82cb6f09d17c2e31593d94141d8da4bbf90b1cc3bd47a7f3676c9cb101623c509fc33387283cf0fc3789d4b0f00d5a88cf0",
          "sha256": "4fb342a8dcd186689adfd6746a3b2b03c4b930f3c8960e9585e7c5594cf3160f",
          "sha1": "a5fc832082202954b704ef4221a57a47adfb675f",
          "md5": "700fcefed717ce6e0385406dd8bfa8da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-test-2.3.4.RELEASE-javadoc.jar",
          "size": 4782,
          "sha512": "4c085cd5a662a9806ca28f89cba56fd1a8a29cbcd7bf152050f975e62c9c25e8be81a256b93a2ebc9ba3c8563a2f0dba688bdc9b223acd580125e232b908a91e",
          "sha256": "2d63a2ad6fafaf4fa8224ed66ac751a4fde5b235873b81f16fe272669eedd010",
          "sha1": "1a158b2ac0a96bdab1b8c4f2c19bcc004ef49364",
          "md5": "fadb68688a8f95a6759d14dab2d8b043"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-starter-test-2.3.4.RELEASE-sources.jar",
          "size": 4782,
          "sha512": "0d696103a2e0cc6bc40a8cf26d502130ec4b5e881c4454b93b10d3ffc25367daa2ccd8ef1b5a8eaedd68dc7052c87bf887f0ada498f375834a5492a8381619b4",
          "sha256": "ae1038e5609d41e64dd781bf090945ec31653833a6dae41d364ebb1b85e88f39",
          "sha1": "cf45e018b1727b1225e5fd41993ebeb0095ba3b7",
          "md5": "365c679044053c5448e7dc3496a8c571"
        }
      ]
    }
  ]
}
