server:
  port: 443

com:
  okaka:
    onenightjinroh:
      domain: https://dev.yuru-jinrou.com

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yuru_jinrou_db
    driver-class-name: org.postgresql.Driver
    username: yuru_jinrou_dev_rw
    password: yuru_jinrou_database_passwd

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

  resources:
    cache:
      period: 0

  web:
    resources:
      cache:
        period: 0