server:
  port: 80 # TODO: 443に変える

com:
  okaka:
    onenightjinroh:
      domain: https://yuru-jinrou.com # TODO: 本番用に変える

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yuru_jinrou_db
    driver-class-name: org.postgresql.Driver
    username: yuru_jinrou_dev_rw
    password: yuru_jinrou_database_passwd

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  resources:
    cache:
      period: 0