server:
  port: 8080

doma:
  dialect: h2

com:
  okaka:
    onenightjinroh:
      domain: http://localhost:8081

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      web-allow-others: true

  datasource:
    url: jdbc:h2:./h2db/testdb?MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  resources:
    cache:
      period: 0