server:
  port: 80

doma:
  dialect: h2

com:
  okaka:
    onenightjinroh:
      domain: https://dev.yuru-jinrou.com

# h2 for debug tool
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      web-allow-others: true

  datasource:
    url: jdbc:postgresql://localhost:5432/yuru_jinrou_db
    driver-class-name: org.postgresql.Driver
    username: yuru_jinrou_dev_rw
    password: yuru_jinrou_database_passwd

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  resources:
    cache:
      period: 0