{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-2.3.4.RELEASE.jar",
          "size": 4763,
          "sha512": "65bf83c3e0564fee7f3796d6cd30423dc6bd51ce48c6b175ec90b77e6f9ddbce5970b7166445dbb498c1abc5fb0759f982cf3fe30e1e406ab162434319f010da",
          "sha256": "777c071bbc57bc76a44989c5c674472d1c1da491743998996a050b418d24a9b0",
          "sha1": "cfeb7cce94a342b4b31b64c42a82c287c2f17207",
          "md5": "043a584ae820281f4f50ded0e98dfac7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-2.3.4.RELEASE.jar",
          "size": 4763,
          "sha512": "65bf83c3e0564fee7f3796d6cd30423dc6bd51ce48c6b175ec90b77e6f9ddbce5970b7166445dbb498c1abc5fb0759f982cf3fe30e1e406ab162434319f010da",
          "sha256": "777c071bbc57bc76a44989c5c674472d1c1da491743998996a050b418d24a9b0",
          "sha1": "cfeb7cce94a342b4b31b64c42a82c287c2f17207",
          "md5": "043a584ae820281f4f50ded0e98dfac7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-2.3.4.RELEASE-javadoc.jar",
          "size": 4763,
          "sha512": "65bf83c3e0564fee7f3796d6cd30423dc6bd51ce48c6b175ec90b77e6f9ddbce5970b7166445dbb498c1abc5fb0759f982cf3fe30e1e406ab162434319f010da",
          "sha256": "777c071bbc57bc76a44989c5c674472d1c1da491743998996a050b418d24a9b0",
          "sha1": "cfeb7cce94a342b4b31b64c42a82c287c2f17207",
          "md5": "043a584ae820281f4f50ded0e98dfac7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-starter-2.3.4.RELEASE-sources.jar",
          "size": 4763,
          "sha512": "04e80c44c31ddc171907684fd9485eaa43c8d5158d74de0dfb12b2e804ebcfe7929623a6d42b78cc2df999257b0ae153c9a408ae5a47c45643c8524c6d838d89",
          "sha256": "04401835b92f3fb5fe4f8b888e3ddd80d31cdb4117b140cf73a1bc1d6f32b800",
          "sha1": "819f6e3ae65f04ba27df3985760914a3b9503fd9",
          "md5": "1bb364f8239f86b8999ed11be41b04a4"
        }
      ]
    }
  ]
}
