name: Build Jinroh and Upload S3
on:
  push:
      branches:
        - test-deploy/pipeline-deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Vue Dependencies
        run: npm install
        working-directory: ./vue

      - name: Build Vue
        run: npm run build-v2
        working-directory: ./vue

      - name: Build Spring boot
        run: ./gradlew bootJar
        working-directory: ./spring

      - name: Zip
        run: |
          cp ./spring/build/libs/one-night-jinroh-0.0.1-SNAPSHOT.jar ./deploy
          zip -r jinroh_deproy.zip ./deploy

      - name: Deploy # S3にデプロイ
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: | # S3のbucket-for-deploying-react-projectバケットにデプロイ
          aws s3 cp --region ap-northeast-1 ./jinroh_deproy.zip s3://okaka-on-jinroh-cd
