name: Build Jinroh and Upload S3 prd
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/yuru-jinrou-github-actions-s3-access-role

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'      

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Install Vue Dependencies
        run: npm install
        working-directory: ./vue

      - name: Build Vue
        run: npm run build-v2
        working-directory: ./vue

      - name: Build Spring boot
        run: ./gradlew bootJar
        working-directory: ./spring

      - name: Zip
        run: |
          cp ./spring/build/libs/one-night-jinroh-0.0.1-SNAPSHOT.jar ./deploy-prd
          zip -r jinroh_deploy.zip ./deploy-prd

      - name: Deploy # S3にデプロイ
        run: | # S3のbucket-for-deploying-react-projectバケットにデプロイ
          aws s3 cp --region ap-northeast-1 ./jinroh_deploy.zip s3://github-actions-s3-upload-test-bucket
